
spike = new User("Spike")
leo = new User("leo")
nikesh = new User("nikesh")
spike.publishPost("Spike first message")
nikesh.publishPost("Nikesh first message")
spike.follow(nikesh)
spike.read()
leo.follow(spike)
leo.follow(nikesh)
leo.read()
